Repository nhsx/au-azure-databricks-cicd, pull requests merged in 2023-03, with the labels that each got.

#271 virtual_ward_current_capacity_v3
  config/pipelines/nhsx-au-analytics/config_virtual_ward_current_capacity_dbrks .json
  config/pipelines/nhsx-au-analytics/config_virtual_ward_dbrks.json
  config/pipelines/reference_tables/config_gp_practice_population_fy_begin.json
Labels: enhancement

#274 Virtual_ward and capacity_build
  analytics/dbrks_virtual_ward/dbrks_secondarycare_virtual_ward_biweekly_current_capacity_and_prop.py
  analytics/dbrks_virtual_ward/dbrks_secondarycare_virtual_ward_patients_biweek_count.py
Labels: enhancement

#276 Fixed Analytics Notebook
  analytics/dbrks_home_care_user_service/dbrks_home_care_user_service.py
  config/pipelines/nhsx-au-analytics/config_home_care_user_service.json
Labels: bug

#277 Changed path
  analytics/dbrks_home_care_user_service/dbrks_home_care_user_service.py
  config/pipelines/nhsx-au-analytics/config_home_care_user_service.json
Labels: bug

#281 bug fix
  ingestion/dbrks_national_digital_channels/dbrks_national_digital_channels_raw.py
Labels: bug

#282 Updated_virtual_ward config_files
  config/pipelines/nhsx-au-analytics/config_virtual_ward_current_capacity_dbrks.json
  config/pipelines/nhsx-au-analytics/config_virtual_ward_dbrks.json
Labels: bug

#283 Updated_Virtual_ward_notebooks
  analytics/dbrks_virtual_ward_current_capacity/dbrks_secondarycare_virtual_ward_biweekly_current_capacity_and_prop.py
  orchestration/dbrks_virtual_ward_current_capacity_orchestrator.py
Labels: bug

#284 Updated Path
  config/pipelines/nhsx-au-analytics/config_virtual_ward_current_capacity_dbrks.json
Labels: bug

#285 Updated registered pop
  config/pipelines/reference_tables/config_gp_practice_population_fy_begin.json
Labels: enhancement

#288 Updated_capacity
  analytics/dbrks_virtual_ward_current_capacity/dbrks_secondarycare_virtual_ward_biweekly_current_capacity_and_prop.py
  orchestration/dbrks_virtual_ward_current_capacity_orchestrator.py
Labels: bug

#296 dsp_nhs_trust_compliance
  config/pipelines/nhsx-au-analytics/config_dspt_nhs_dbrks.json
Labels: enhancement

#297 Dspt_path_update_v5
  config/pipelines/nhsx-au-analytics/config_dspt_nhs_dbrks.json
Labels: bug

#298 Dspt_nhs_trust_icb
  analytics/dbrks_dspt_nhs/dbrks_cybersecurity_dspt_nhs_trusts_standards_compliance_by_ICB.py
Labels: enhancement

#299 Dpst_social_care_comploiance
  config/pipelines/nhsx-au-analytics/config_dspt_nhs_dbrks.json
Labels: enhancement

#302 Updating_Dpst_nhs_trust
  config/pipelines/nhsx-au-analytics/config_dspt_nhs_dbrks.json
Labels: documentation

#304 Social_care_compliance_by_ICB
  config/pipelines/nhsx-au-analytics/config_dspt_socialcare_dbrks.json
Labels: enhancement

#306 Updated a path
  config/pipelines/nhsx-au-analytics/config_dspt_socialcare_dbrks.json
Labels: bug

#310 Corrected post validation on config file
  config/pipelines/nhsx-au-analytics/config_virtual_ward_current_capacity_dbrks.json
Labels: bug
