Repository nhsx/au-azure-databricks-cicd, pull requests merged in 2023-05, with the labels that each got.

#348 Ers update
  config/pipelines/direct-load/config_ers_api.json
Labels: enhancement

#349 Adde ers orchestrator
  orchestration/dbrks_e_rs_api_orchestrator.py
Labels: enhancement

#351 Added processing notebooks for ers
  direct-load/dbrks_e_rs_api/dbrks_e_rs_api_month_count.py
  direct-load/dbrks_e_rs_api/dbrks_e_rs_api_month_prop.py
Labels: enhancement

#355 Fixing the esr month count
  direct-load/dbrks_e_rs_api/dbrks_e_rs_api_month_count.py
  orchestration/dbrks_e_rs_api_orchestrator.py
Labels: bug

#359 ESR_Fixing
  config/pipelines/nhsx-au-analytics/config_esr_api.json
Labels: bug

#360 ESR_Api_Rewok
  analytics/dbrks_e_rs_api/dbrks_e_rs_api_month_count.py
  analytics/dbrks_e_rs_api/dbrks_e_rs_api_month_prop.py
  orchestration/dbrks_e_rs_api_orchestrator.py
Labels: bug

#361 Corrected
  analytics/dbrks_e_rs_api/dbrks_e_rs_api_month_count.py
  analytics/dbrks_e_rs_api/dbrks_e_rs_api_month_prop.py
  orchestration/dbrks_e_rs_api_orchestrator.py
Labels: bug

#362 Updated_paths_v7
  analytics/dbrks_e_rs_api/dbrks_e_rs_api_month_count.py
  analytics/dbrks_e_rs_api/dbrks_e_rs_api_month_prop.py
Labels: bug

#363 Updating_notebook_paths
  config/pipelines/nhsx-au-analytics/config_esr_api.json
Labels: bug

#364 Added a new notebook
  config/pipelines/nhsx-au-analytics/config_esr_api.json
Labels: bug, enhancement

#371 Update_v9
  config/pipelines/nhsx-au-analytics/config_esr_api.json
Labels: bug

#372 updated_v9
  analytics/dbrks_e_rs_api/dbrks_e_rs_api_month_prop_by_ICB.py
Labels: bug

#373 Adde_notebook_range
  analytics/dbrks_e_rs_api/dbrks_e_rs_api_month_prop_by_ICB.py
Labels: bug

#374 Added_raw_location
  config/pipelines/nhsx-au-analytics/config_esr_api.json
Labels: bug

#375 added injestion
  ingestion/dbrks_e_rs_api/dbrks_e_rs_api_raw.py
Labels: bug

#376 ESR_Update_v10
  config/pipelines/nhsx-au-analytics/config_esr_api.json
Labels: bug

#377 updated_injestion_notebook
  ingestion/dbrks_e_rs_api/dbrks_e_rs_api_raw.py
Labels: bug

#378 datestringchange
  ingestion/dbrks_e_rs_api/dbrks_e_rs_api_raw.py
Labels: bug

#387 updated_latesttdate
  analytics/dbrks_e_rs_api/dbrks_e_rs_api_month_prop_by_ICB.py
Labels: bug

#342 Ct validation update
  validation/dbrks_nhs_app_validation/dbrks_trigger_nhs_app_validation.py
Labels: enhancement

#391 Added notebook for M271
  analytics/dbrks_national_digital_channels/dbrks_ndc_dashboard_user_base_loggingin_3month_prop.py
Labels: enhancement

#393 ESR_validation
  config/pipelines/direct-load/config_ers_api.json
Labels: enhancement

#394 ESR_Validation
  validation/dbrks_e_rs_api_validation/dbrks_e_rs_api_file_validation.py
Labels: enhancement

#395 Config_correction
  validation/dbrks_e_rs_api_validation/dbrks_e_rs_api_file_validation.py
Labels: bug

#399 Clinical_trial_epr_ingestion_orchestrator
  ingestion/dbrks_clinical_trial/dbrks_clinical_trial_raw.py
  ingestion/dbrks_epr/dbrks_epr_raw.py
  orchestration/dbrks_clinical_trial_orchestrator.py
  orchestration/dbrks_epr_orchestrator.py
Labels: enhancement

#406 Range change
  analytics/dbrks_e_rs_api/dbrks_e_rs_api_month_count.py
Labels: bug

#407 bug fix index error
  analytics/dbrks_e_rs_api/dbrks_e_rs_api_month_count.py
Labels: bug

#408 Updated_paths
  config/pipelines/nhsx-au-analytics/config_clinical_trial_dbrks.json
Labels: enhancement

#411 EPR_analytics_build
  analytics/dbrks_epr/dbrks_epr_data_biweekly_count.py
Labels: enhancement

#412 EPR_Date_update
  ingestion/dbrks_epr/dbrks_epr_raw.py
Labels: bug

#413 Added_date path
  ingestion/dbrks_epr/dbrks_epr_raw.py
Labels: bug

#414 Analytical_correction
  analytics/dbrks_epr/dbrks_epr_data_biweekly_count.py
Labels: bug

#415 removing validation file fix
  config/pipelines/nhsx-au-analytics/config_epr_dbrks.json
Labels: bug

#417 quick_correction
  config/pipelines/nhsx-au-analytics/config_clinical_trial_dbrks.json
  config/pipelines/nhsx-au-analytics/config_epr_dbrks.json
Labels: bug

#420 epr config file bug fix
  config/pipelines/nhsx-au-analytics/config_epr_dbrks.json
Labels: bug

#425 virtual_ward_rebuild
  config/pipelines/nhsx-au-analytics/virtual_ward_capacity.json
Labels: enhancement

#429 Rebuilding_virtual_ward_capacity
  analytics/dbrks_virtual_ward_capacity/dbrks_virtual_ward_biweekly_capacity_and_prop.py
  ingestion/dbrks_virtual_ward_capacity/dbrks_virtual_ward_capacity_raw.py
  orchestration/dbrks_virtual_ward_capacity_orchestrator.py
Labels: enhancement
