Repository nhsx/au-azure-databricks-cicd, pull requests merged in 2023-02, with the labels that each got.

#238 Ct shared care databricks
  ingestion/dbrks_shared_care_record/dbrks_shared_care_record_raw.py
Labels: enhancement

#250 changes version type on openpyxl for compatibility reasons
  ingestion/dbrks_shared_care_record/dbrks_shared_care_record_raw.py
Labels: bug

#253 added config file for home care user
  config/pipelines/nhsx-au-analytics/config_home_care_user_service.json
Labels: enhancement

#254 Ingestion Notebook added
  ingestion/dbrks_home_care_user_service/dbrks_home_care_user_service_raw.py
Labels: enhancement

#255 Ingestion home care user service
  ingestion/dbrks_home_care_user_service/dbrks_home_care_user_service_raw.py
Labels: enhancement

#256 Added home care service user analytics notebook
  analytics/dbrks_dscr/dbrks_dscr_all_variables_care_home_beds.py
  analytics/dbrks_home_care_user_service/dbrks_home_care_user_service_count.py
  ingestion/dbrks_home_care_user_service/dbrks_home_care_user_service_raw.py
Labels: enhancement

#257 Virtual ward and icb pop latest
  config/pipelines/reference_tables/config_gp_practice_population_fy_begin.json
  config/pipelines/reference_tables/config_icb_population.json
Labels: enhancement

#259 Virtual_ward_and_registered_populatuin
  analytics/dbrks_virtual_ward/dbrks_secondarycare_virtual_ward_patients_biweek_count.py
  analytics/dbrks_virtual_ward/dbrks_secondarycare_virtual_ward_patients_biweek_rate.py
  ingestion/dbrks_registered_gp_practices_fy_begin_population/dbrks_registered_gp_practices_fy_begin_population_raw.py
  orchestration/dbrks_virtual_ward_orchestrator.py
Labels: enhancement

#258 virtual ward build
  config/pipelines/nhsx-au-analytics/config_virtual_ward_dbrks.json
Labels: documentation

#261 Updated virtaul ward analytical notebook
  analytics/dbrks_virtual_ward/dbrks_secondarycare_virtual_ward_patients_biweek_count.py
Labels: bug

#262 Updated the capacity query
  analytics/dbrks_virtual_ward/dbrks_secondarycare_virtual_ward_patients_biweek_count.py
Labels: bug

#260 Added code on data processing notebook
  analytics/dbrks_home_care_user_service/dbrks_home_care_user_service_count.py
Labels: enhancement

#264 Updated config file
  config/pipelines/nhsx-au-analytics/config_home_care_user_service.json
Labels: bug

#268 updated notebook
  ingestion/dbrks_nhs_app_logins/dbrks_nhs_app_logins_raw.py
Labels: enhancement
