Repository nhsx/au-azure-databricks-cicd, pull requests merged in 2023-07, with the labels that each got.

#466 Corrected_Vw_notebook
  analytics/dbrks_virtual_ward_capacity/dbrks_virtual_ward_biweekly_capacity_and_prop.py
Labels: bug

#474 Ct messages update
  analytics/dbrks_national_digital_channels/dbrks_ndc_messages_nhsapp_messages_read.py
  ingestion/dbrks_national_digital_channels/dbrks_national_digital_channels_raw.py
Labels: enhancement

#475 naming tweaks
  config/pipelines/nhsx-au-analytics/config_national_digital_channels_dbrks.json
Labels: bug

#478 new notebook for notifications
  analytics/dbrks_national_digital_channels/dbrks_ndc_messages_nhsapp_notifications_only.py
  ingestion/dbrks_national_digital_channels/dbrks_national_digital_channels_raw.py
Labels: enhancement

#480 source file name fix
  analytics/dbrks_national_digital_channels/dbrks_ndc_messages_nhsapp_messages_read.py
Labels: bug

#481 correction to config
  config/pipelines/nhsx-au-analytics/config_national_digital_channels_dbrks.json
Labels: bug

#482 column name correction
  analytics/dbrks_national_digital_channels/dbrks_ndc_messages_nhsapp_notifications_only.py
Labels: bug

#487 DSPT_yearly_update
  analytics/dbrks_dspt_nhs/dbrks_cybersecurity_dspt_nhs_csu_ccg_standards_month_count_prop.py
  analytics/dbrks_dspt_nhs/dbrks_cybersecurity_dspt_nhs_trusts_standards_month_count_prop.py
Labels: documentation
