Repository nhsx/au-azure-databricks-cicd, pull requests merged in 2023-09, with the labels that each got.

#505 adjusted M235 calculations
  analytics/dbrks_national_digital_channels/dbrks_ndc_transactions_nhsapp_appointment_management_month_count.py
Labels: bug

#506 DSPT_GP_practices_Update
  analytics/dbrks_dspt_gp_practices/dbrks_cybersecurity_dspt_gp_practices_standards_exceed_month_count_prop.py
  analytics/dbrks_dspt_gp_practices/dbrks_cybersecurity_dspt_gp_practices_standards_meet_exceed_month_count_prop.py
  analytics/dbrks_dspt_gp_practices/dbrks_cybersecurity_dspt_gp_practices_standards_nosubmission_month_count_prop.py
Labels: documentation

#508 Shared care update
  ingestion/dbrks_shared_care_record/dbrks_shared_care_record_raw.py
Labels: enhancement

#509 update to shared care config
  config/pipelines/nhsx-au-analytics/config_shared_care_record_dbrks.json
Labels: enhancement

#510 config corrections
  config/pipelines/nhsx-au-analytics/config_shared_care_record_dbrks.json
Labels: bug

#511 Ct shared care databricks update
  ingestion/dbrks_shared_care_record/dbrks_shared_care_record_raw.py
Labels: enhancement

#516 Updates to shared
  ingestion/dbrks_shared_care_record/dbrks_shared_care_record_raw.py
Labels: bug

#518 EPR_Update
  analytics/dbrks_epr/dbrks_epr_data_biweekly_count.py
Labels: enhancement

#525 Ct ndc update
  analytics/dbrks_national_digital_channels/dbrks_ndc_dashboard_nhsapp_secondary_care_appointments_month_count.py
  analytics/dbrks_national_digital_channels/dbrks_ndc_transactions_nhsapp_wayfinder.py
Labels: bug

#526 tweak to code
  analytics/dbrks_national_digital_channels/dbrks_ndc_dashboard_nhsapp_secondary_care_appointments_month_count.py
Labels: bug

#527 fix to code
  analytics/dbrks_national_digital_channels/dbrks_ndc_dashboard_nhsapp_secondary_care_appointments_month_count.py
Labels: bug

#530 adjustment
  analytics/dbrks_nhs_app/dbrks_nhs_app_jumpoff_all_dynamic.py
Labels: enhancement
